services:

  postgresDb:
    image: postgres:14
    container_name: postgres-backend-example
    environment:
      POSTGRES_USER: ${dbUser}
      POSTGRES_PASSWORD: ${dbPassword}
      POSTGRES_DB: ${dbName}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    container_name: mongo-backend-example
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${dbUser}
      MONGO_INITDB_ROOT_PASSWORD: ${dbPassword}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: